name: Salesforce Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # -----------------------------
      # Setup
      # -----------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      # -----------------------------
      # Authenticate TEST
      # -----------------------------
      - name: Authenticate TEST Org
        run: |
          echo "${{ secrets.SF_AUTH_TEST }}" > auth_test.txt
          sf org login sfdx-url --sfdx-url-file auth_test.txt --alias TEST

      # -----------------------------
      # Authenticate LOAD
      # -----------------------------
      - name: Authenticate LOAD Org
        run: |
          echo "${{ secrets.SF_AUTH_LOAD }}" > auth_load.txt
          sf org login sfdx-url --sfdx-url-file auth_load.txt --alias LOAD

      # -----------------------------
      # Deploying to TEST
      # -----------------------------
      - name: Deploy to TEST
        run: |
          sf project deploy start \
            --target-org TEST \
            --test-level NoTestRun

      # -----------------------------
      # Deploying to LOAD
      # -----------------------------
      - name: Deploy to LOAD
        run: |
          sf project deploy start \
            --target-org LOAD \
            --test-level NoTestRun